spring:
  profiles.active: dev
  main:
    web-application-type: reactive

# see https://www.baeldung.com/spring-rest-openapi-documentation
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui/index.html

logging:
  level:
    io.netty: INFO
    io.smetweb: TRACE
    com.zaxxer.hikari: INFO
    org.hibernate: INFO
    org.springframework: INFO
