spring:
  profiles.active: dev
---
spring:
  profiles: dev
# enables http://localhost:8080/h2-console/ (https://www.baeldung.com/spring-boot-hibernate)
  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    io.netty: INFO
    io.smetweb: TRACE
#logging.level.root=info
#logging.level.io.smetweb=trace
#logging.level.com.zaxxer.hikari=INFO
#logging.level.org.hibernate=INFO
