spring:
  profiles: dev

  main:
    banner-mode: off

  # enables http://localhost:8080/h2-console/ (https://www.baeldung.com/spring-boot-hibernate)
  h2:
    console:
      enabled: true
      path: /h2-console

smetweb:
  http-port: 8081
  name: dev-host
#  url: nonnull
#  email-address: nonnull

scenario:
  setup-name: dev-setup
  random-seed: -1

logging:
  level:
    io.smetweb: TRACE
    org.springframework: INFO
    com.zaxxer.hikari: INFO
    org.hibernate: INFO
    io.netty: INFO

